"""empty message

Revision ID: 0b6b5b6b2874
Revises: 68f8e0b02e3b
Create Date: 2021-04-13 02:46:21.239472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b6b5b6b2874'
down_revision = '68f8e0b02e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('favorites', 'date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###
