"""empty message

Revision ID: 3b06866aa864
Revises: 0b6b5b6b2874
Create Date: 2021-04-14 00:53:29.370780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b06866aa864'
down_revision = '0b6b5b6b2874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
