"""empty message

Revision ID: 68f8e0b02e3b
Revises: 36928abbea6a
Create Date: 2021-04-10 01:42:13.826160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f8e0b02e3b'
down_revision = '36928abbea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('films', 'title2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('title2', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('films', 'title')
    # ### end Alembic commands ###
