"""empty message

Revision ID: 7b29211730a6
Revises: dd4126b117de
Create Date: 2021-04-10 01:40:18.192254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b29211730a6'
down_revision = 'dd4126b117de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('director', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'director')
    # ### end Alembic commands ###
