"""empty message

Revision ID: d2e1e5586f81
Revises: 9518be0ec79d
Create Date: 2021-04-09 01:25:08.428528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2e1e5586f81'
down_revision = '9518be0ec79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('date', sa.String(length=10), nullable=False))
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', mysql.VARCHAR(length=28), nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    op.drop_column('favorites', 'date')
    # ### end Alembic commands ###
