"""empty message

Revision ID: dd4126b117de
Revises: d2e1e5586f81
Create Date: 2021-04-09 01:48:34.298434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4126b117de'
down_revision = 'd2e1e5586f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('films_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('people_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'films', ['films_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'people', ['people_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'planets', ['planets_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planets_id')
    op.drop_column('favorites', 'people_id')
    op.drop_column('favorites', 'films_id')
    # ### end Alembic commands ###
